products/urls.py
from django.urls import path

# Импортируем контроллеры
from products.views import products, basket_add, basket_delete

# Обязательно создаётся переменная app_name с названием нашего приложения 'products'. Это позволяет django понимать к какому приложению относятся ниже приведённые маршруты
app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('<int:category_id>/', products, name='category'),
    path('page/<int:page>/', products, name='page'),
    path('basket-add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket-delete/<int:id>/', basket_delete, name='basket_delete'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include # Импортируется include для пространства имён
from django.conf.urls.static import static
from django.conf import settings

from products.views import index, test_context   # Импорт функции из файла products/views.py

# В urlpattern первым параметров указывается адрес, по которому будет отображаться страница,  а вторым - сама страница, которая будет отображаться
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),   # Путь к главной странице сайта. Из-за пустого первого параметра ('') при переходе на наш сайт / проект будет открываться наша главная старница, которую мы описали как index и которая вызывается функцией index из файла products/views.py
    path('products/', include('products.urls', namespace='products')), # Также тут примененно пространство имён и все маршруты с products теперь имеют пространство имён "products" и обрабатываются приложением products
    path('users/', include('users.urls', namespace='users')),  # При переходе на наш сайт / проект будет открываться страница с пользователями, которую мы описали как users и которая вызывается функцией users из файла users/views.py.
    path('test-context/', test_context, name = 'test_context'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Добавляем обработку медиафайлов в режиме отладки. Это нужно для того, чтобы при отладке проекта можно было видеть изображения, которые мы загружаем в папку media
    # MEDIA_URL - это URL-адрес, по которому будут доступны медиафайлы
    # MEDIA_ROOT - это путь к папке, где будут храниться медиафайлы

users/urls.py
from django.urls import path

# Импортируем контроллеры
from users.views import login, register, profile, logout

# Обязательно создаётся переменная app_name с названием нашего приложения 'products'. Это позволяет django понимать к какому приложению относятся ниже приведённые маршруты
app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'), 
]

products/models.py
from django.db import models

from users.models import User

# Модели в Django - это обычные классы в Pyton
# Пустой класс или модель в Django создать нельзя. Он всегда унаследован от models.Model.
# Поле id или primary_key в Django создаётся автоматически, если не указано иное.
# Если в качестве primaty_key хочется использовать другое поле, то нужно указать primary_key=True в этом поле и тогда это поле станет первичным ключом модели: name = models.CharField(max_length=64, unique=True, verbose_name='Наименование категории', primary_key=True)
 
class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Наименование категории')    # unique=True означает, что данное поле должно быть уникальным
    description = models.TextField(blank=True, verbose_name='Описание категории')   # Специальный класс для поля с большим кол-вом текста. blant=True позволяет полю быть пустым
    
    class Meta:
        verbose_name_plural = 'Product Categories'
        
    def __str__(self):
        return f"{self.name}"

class Product(models.Model):
    name = models.CharField(max_length=256, unique=True, verbose_name='Наименование товара')
    image = models.ImageField(upload_to='products_images/', blank=True, verbose_name='Изображение товара')  # upload_to - путь к папке, куда будут загружаться изображения. Папка products будет создана в MEDIA_ROOT
    description = models.TextField(blank=True, verbose_name='Описание товара')
    short_description = models.CharField(max_length=64, blank=True, verbose_name='Краткое описание товара')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена товара', blank=False, default=0)
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество товара')  # PositiveIntegerField - поле для положительных целых чисел
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='products', verbose_name='Категория товара')  # Связь с моделью ProductCategory.  on_delete=models.PROTECT охначает, что при удалении категории будут одновременно удалены и все товары ,которые в неё входят. on_delete=models.PROTECT означает, что категорию нельзя удалить пока хотя бы один товар в ней есть. related_name='products' - позволяет получить все товары в категории через category.products.all()
    is_active = models.BooleanField(default=True, verbose_name='Активность товара')
    
    def __str__(self):
        return f"{self.category.name} | {self.name}"
    
class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestap = models.DateTimeField(auto_now_add=True)
    
    def sum(self):
        """ Method to calculate the total price of the product in the basket """
        
        return self.product.price * self.quantity
    
    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'
    

products/views.py
"""
Views - это так называемые контроллеры, которые отвечают за работу определённо логики или функций или за отображение определённых шаблонов.
Views - это просто функции, которые вызываются.
"""

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required  # Декоратор, который позволяет ограничить доступ к показу страниц только для авторизованных пользователей
from django.core.paginator import Paginator  # Импортируем Paginator для постраничного отображения товаров

from products.models import ProductCategory, Product, Basket

def index(request):
    # В данном случае возвращается результат - функция render, которая и рендерит (создаёт) определённую страницу.
    # В фукнцию render обязательно передаётся первый параметр - request.
    # Для возвращения срендеринной страницу нужно указать сам запрос, который мы передали, и путь к шаблону той страницы, которую мы возвращаем.
    # У нас в папке product есть папка templates и django понимает, что в этой папке лежат шаблоны.
    # Т.е. когда django нужен шаблон из products она сама найдёт папку templates и в ней найдёт шаблон.
    # Для того, чтобы страница отображалась нужно указать путь к ней в файле urls.py в корневой папке приложения.
    context = {
        'title': "Store"
    }
    return render(request, 'products/index.html', context)

def products(request, category_id=None, page=1):
    """ Method to display all products in the store """
    
    context = {
        'title': "Store - Каталог",
        'categories': ProductCategory.objects.all(),    # Получаем все категории продуктов из базы данных
    }
    
    if category_id:
        products = Product.objects.filter(category_id=category_id)  # Фильтруем товары по категории
        
    else:
        products = Product.objects.all()  # Получаем все товары из базы данных
        # context.update({'products': Product.objects.all()})  # Получаем все товары из всех категория в базе данных
        
    paginator = Paginator(products, 3)  # Создаём пагинатор, который будет разбивать товары на страницы по 3 товара на странице
    products_paginator = paginator.page(page)  # Получаем текущую страницу с товарами
    context.update({'products': products_paginator})  # Получаем / фильтруем товары на странице по категории
    return render(request, 'products/products.html', context)

@login_required  # Декоратор, который позволяет ограничить доступ к показу страниц только для авторизованных пользователей
def basket_add(request, product_id):
    """ Method to add a product to the basket """
    
    current_page = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=product_id)
    basket = Basket.objects.filter(user=request.user, product=product)
    
    if not basket.exists():    # Метод exsists применяется только для списков
        basket = Basket(user=request.user, product=product, quantity=1)
        basket.save()
        # Второй способ создать объект корзины, если его ещё нет у пользователя
        # Basket.objects.create(user=request.user, product=product, quantity=1)
        return redirect(current_page)   # Возвращаем пользователя на ту же страницу, на которой он находится сейчас
    else:
        basket = basket.first()
        basket.quantity += 1
        basket.save()
        return redirect(current_page)

def basket_delete(request, id):
    """ Method to delete a product from the basket"""
    
    basket = Basket.objects.get(id=id)
    basket.delete()
    return redirect(request.META.get('HTTP_REFERER'))

def test_context(request):
    """ Method to test context data in a template """
    
    context = {
        'title': 'store',
        'header': 'Welcome to our store!',
        'username': 'John Doe',
        'products': [
            {'name': 'Худи черного цвета с монограммами adidas Originals',
            'price': 6990.00,
            'description': 'Мягкая ткань для свитшотов. Стиль и комфорт – это образ жизни.'
            },
            {'name': 'Синяя куртка The North Face',
            'price': 23725.00,
            'description': 'Гладкая ткань. Водонепроницаемое покрытие. Легкий и теплый пуховый наполнитель.'
            },
            {'name': 'Коричневый спортивный oversized-топ ASOS DESIGN',
            'price': 3390.00,
            'description': 'Материал с плюшевой текстурой. Удобный и мягкий.'
            }
        ],
        'products_of_promotion': [
            {'name': 'Коричневый спортивный oversized-топ ASOS DESIGN',
            'price': 1500.00,
            'description': 'Материал с плюшевой текстурой. Удобный и мягкий.'
            }
        ]
    }
    return render(request, 'products/test-context.html', context)

store/products/views.py
from django.shortcuts import render

def index(request):
    # В данном случае возвращается результат функции render - она рендерит определённую страницу
    # В фукнцию render обязательно передаётся первый параметр - request и второй параметр - template name или путь к шаблону,
    # который нужно отрендерить / отобразить
    return render(request, 'products/index.html')

def products(request):
    return render(request, 'products/products.html')

def test_context(request):
    context = {
        'title': 'store',
        'header': 'Welcome to our store!',
        'username': 'John Doe',
        'products': [
            {
                'name': 'Худи черного цвета с монограммами adidas Originals',
                    'price': 6990.00,
                    'description': 'Мягкая ткань для свитшотов. Стиль и комфорт – это образ жизни.'
            },
            {
                'name': 'Синяя куртка The North Face',
                    'price': 23725.00,
                    'description': 'Гладкая ткань. Водонепроницаемое покрытие. Легкий и теплый пуховый наполнитель.'
            },
            {
                'name': 'Коричневый спортивный oversized-топ ASOS DESIGN',
                    'price': 3390.00,
                    'description': 'Материал с плюшевой текстурой. Удобный и мягкий.'
            }
        ],
        'products_of_promotion': [
            {
                'name': 'Коричневый спортивный oversized-топ ASOS DESIGN',
                    'price': 1500.00,
                    'description': 'Материал с плюшевой текстурой. Удобный и мягкий.'
            }
        ]
    }
    return render(request, 'products/test-context.html', context)

products/templates/products/base.html
{% comment %} При помощи шаблонного тега указываем путь к папке static {% endcomment %}
{% load static %}
{% comment %} После этого можно заменить static по всех путях к каким-либо файлам {% endcomment %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>{{ title|title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i></a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}<i class="fas fa-user-circle"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
              </li>
            {% endif %}
            
            
          </ul>
        </div>
      </div>
    </nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- FontAwesome script -->
    <script
      src="{% static 'vendor/fontawesome/fontawesome-icons.js' %} "
      crossorigin="anonymous"
    ></script>
  </body>
</html>

products/templates/products/basket.html
{% if baskets %}
    <div class="col-lg-5">
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
        </h4>
        {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.shot_description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between lh-condensed bg-light">
                        <span class="text-muted">{{ basket.quantity }}</span>
                        <span class="text-muted">{{ basket.sum }}</span>
                        <span class="text-muted">
                            <a href="{% url 'products:basket_add' basket.product.id %}" style="text-decoration: none; color: gray;">
                                <i class="fas fa-cart-plus"></i>
                            </a> 
                            <a href="{% url 'products:basket_delete' basket.id %}" style="text-decoration: none; color: gray;">
                                <i class="far fa-trash-alt"></i>
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
        {% endfor %}
        
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                <h4 class="float-right">{{ total_sum }}</h4>
            </div>
        </div>

    <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
    </div>
{% else %}
    <h4 class="mt-3 mb-3">
    Корзина пуста
    </h4>
{% endif %}

products/templates/products/index.html
{% extends 'products/base.html' %}
{% comment %} Наследуемся от BASE.html при помощи шаблонного тега {% endcomment %}

{% comment %} Важно помнить, что статика (static) подгружаестся и на всех страницах, которые наследуются от основного шаблона {% endcomment %}
{% comment %} При помощи шаблонного тега указываем путь к папке static {% endcomment %}
{% load static %}

{% block title %}
{% endblock %}

{% comment %} Теперь обращаемся к блокам, которые общие для всех страниц и прописаны в шаблоне, от которого наследуемся {% endcomment %}
{% comment %} На этой странице ставляется CSS-файл для страницы index {% endcomment %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% comment %} Дальше идёт блок content для конкретной страницы {% endcomment %}
{% block content %}
  <!-- Page Content -->
  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <h1 class="mt-5">Store</h1>
          <p>
            Новые образы и лучшие бренды Store. Бесплатная доставка по всему
            миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
          </p>
          <button id="start-purchase-btn" type="button" class="btn btn-lg"><a id="start-purchase-link" href="{% url 'products:index' %}">Начать покупки</a>
          </button>
        </div>
      </div>
    </div>
  </section>
{% endblock %}




{% comment %} После этого можно заменить static по всех путях к каким-либо файлам {% endcomment %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Store</title>

    <!-- Bootstrap core CSS -->
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'products' %}"
                >Каталог <i class="fas fa-shopping-bag"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="auth/login.html"
                >Войти <i class="fas fa-sign-in-alt"></i
              ></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="auth/profile.html"
                >Валерий П.
                <i class="fas fa-user-circle"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"
                >Выйти <i class="fas fa-sign-out-alt"></i
              ></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- FontAwesome script -->
    <script
      src="{% static 'vendor/fontawesome/fontawesome-icons.js' %} "
      crossorigin="anonymous"
    ></script>
  </body>
</html>

products/templates/products/products.html
{% extends "products/base.html" %}
{% comment %} Наследуемся от BASE.html при помощи шаблонного тега {% endcomment %}

{% load static %}
{% comment %} Важно помнить, что статика (static) должна конкретно подгружаться и на всех страницах, которые наследуются от основного шаблона. При помощи шаблонного тега указываем путь к папке static {% endcomment %}

{% block title %}
{% endblock %}

{% comment %} Теперь обращаемся к блокам, которые общие для всех страниц и прописаны в шаблоне, от которого наследуемся {% endcomment %}
{% comment %} На этой странице вставляется CSS-файл для страницы index {% endcomment %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/products.css' %}">
{% endblock %}

{% block content %}
<!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-3">
          <h1 class="my-4">Store</h1>
          <div class="list-group">
            {% for category in categories %}
              <a href="{% url 'products:category' category.id %}" class="list-group-item">{{ category.name }}</a>
            {% endfor %}
          </div>
        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
          <div
            id="carouselExampleIndicators"
            class="carousel slide my-4"
            data-ride="carousel"
          >
            <ol class="carousel-indicators">
              <li
                data-target="#carouselExampleIndicators"
                data-slide-to="0"
                class="active"
              ></li>
              <li
                data-target="#carouselExampleIndicators"
                data-slide-to="1"
              ></li>
              <li
                data-target="#carouselExampleIndicators"
                data-slide-to="2"
              ></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img
                  class="d-block img-fluid"
                  src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                  alt="First slide"
                />
              </div>
              <div class="carousel-item">
                <img
                  class="d-block img-fluid"
                  src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                  alt="Second slide"
                />
              </div>
              <div class="carousel-item">
                <img
                  class="d-block img-fluid"
                  src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                  alt="Third slide"
                />
              </div>
            </div>
            <a
              class="carousel-control-prev"
              href="#carouselExampleIndicators"
              role="button"
              data-slide="prev"
            >
              <span
                class="carousel-control-prev-icon"
                aria-hidden="true"
              ></span>
              <span class="sr-only">Previous</span>
            </a>
            <a
              class="carousel-control-next"
              href="#carouselExampleIndicators"
              role="button"
              data-slide="next"
            >
              <span
                class="carousel-control-next-icon"
                aria-hidden="true"
              ></span>
              <span class="sr-only">Next</span>
            </a>
          </div>

          <div class="row">
            {% for product in products %}
              <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                  <a href="#">
                    <img
                      class="card-img-top"
                      src="/media/{{ product.image }}"
                      alt=""
                    />
                  </a>
                  <div class="card-body">
                    <h4 class="card-title">
                      <a href="#">{{ product.name }}</a>
                    </h4>
                    <h5>{{ product.price }}</h5>
                    <p class="card-text">{{ product.short_description }}</p>
                  </div>
                  <div class="card-footer text-center">
                    <a href="{% url 'products:basket_add' product.id %}"><button type="button" class="btn btn-outline-success">Отправить в корзину</button></a>
                    
                  </div>
                </div>
              </div>
            {% endfor %}
            
          </div>

          <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
              <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                <a class="page-link" href="{% if products.has_previous  %} {% url 'products:page' products.previous_page_number %} {% else %} # {% endif %}" tabindex="-1" aria-disabled="true"
                  >Назад</a
                >
              </li>
            {% for page in products.paginator.page_range %}
              <li class="page-item"><a class="page-link" href="{% url 'products:page' page %}">{{ page }}</a></li>
            {% endfor %}
              <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if products.has_next  %} {% url 'products:page' products.next_page_number %} {% else %} # {% endif %}">Вперёд</a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
{% endblock %}

{% block footer %}
<!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; <a class="navbar-brand" href="{% url 'index' %}">Store 2021</a></p>
        
      </div>
      <!-- /.container -->
    </footer>
{% endblock%}

products/templates/products/test-context.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title|title }}</title>
    <!--Тут использован placholder. Также применён метод title, который переводит строку в строку с заглавной буквы, т.е. первый title - это placeholder, в второй title - это уже метод, который к первому title применяется-->
  </head>
  <body>
    <h1>{{ header }}</h1>
    <!--И тут использован placeholder -->
    <p>{{ username }}</p>
    <!--И тут использован placeholder -->
    <!--Но placeholder не годится для действий, связанных с итерацией по спискам и вывода значений этого списка-->
    <!--Для итераций используется шаблонный тег-->
    {% if products %}
      {% for product in products %}
        <h4>{{ product.name}}</h4>
        <!-- Здесь мы уже используем placeholder -->
        <p>{{ product.price }} долл.США</p>
        <!-- Шаблонный тег обязательно и всегда закрывается-->
      {% endfor %}
    {% endif %}

    {% if products_of_promotion %}
      <h3 style="color: red;">Товары по акции</h3>
      {% for product in products_of_promotion %}
        <h4>{{ product.name}}</h4>
        <!-- Здесь мы уже используем placeholder -->
        <p>{{ product.price }} долл.США</p>
        <!-- Шаблонный тег обязательно и всегда закрывается-->
      {% endfor %}
    {% endif %}

  </body>
</html>